apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: nifi

resources:
- ./nifi-pdb.yaml
- ./nifi-web-service.yaml
- ./nifi-headless-service.yaml
- ./nifi-statefulset.yaml
