apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  serviceName: nifi-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    spec:
      containers:
      - name: nifi
        image: dbkegley/nifi:1.8.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        - containerPort: 6342
        - containerPort: 10000
        - containerPort: 10443
        - containerPort: 11443
        readinessProbe:
          exec:
            command:
            - bash
            - "-c"
            - "curl http://127.0.0.1:8081/nifi"
          initialDelaySeconds: 300
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 300
          periodSeconds: 15
        volumeMounts: # https://groups.google.com/forum/#!topic/openshift/klwlwl2m-uE
        - name: data
          mountPath: /opt/nifi/nifi-current/flowfile_repository
          subPath: flowfile_repository
        - name: data
          mountPath: /opt/nifi/nifi-current/database_repository
          subPath: database_repository
        - name: data
          mountPath: /opt/nifi/nifi-current/content_repository
          subPath: content_repository
        - name: data
          mountPath: /opt/nifi/nifi-current/provenance_repository
          subPath: provenance_repository
        env:
        - name: NIFI_WEB_HTTP_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIFI_WEB_HTTP_PORT
          value: "8081"
        - name: NIFI_CLUSTER_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIFI_WEB_PROXY_HOST
          value: ""
        - name: NIFI_CLUSTER_IS_NODE
          value: "true"
        - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
          value: "11443"
        - name: NIFI_ZK_ROOT_NODE
          value: "/nifi" # This value must be unique for each nifi cluster deployment if multiple are using the same zk cluster
        - name: NIFI_ZK_CONNECT_STRING
          value: "zookeeper-0.zk-hs.b23-data-platform.svc.cluster.local:2181,zookeeper-1.zk-hs.b23-data-platform.svc.cluster.local:2181,zookeeper-2.zk-hs.b23-data-platform.svc.cluster.local:2181"
        - name: NIFI_ELECTION_MAX_WAIT
          value: "60 sec"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: nifi-storage-class
