nifi_endpoint: http://nifi-dev:8080
component_dir: components

max_event_driven_threads: 10
max_timer_driven_threads: 6

reporting_task_controllers:
- name: graphite-metrics-service
  config:
    package_id: org.apache.nifi.metrics.reporting.reporter.service.GraphiteMetricReporterService
    properties:
      host: '127.0.0.1'
      port: '8080'
      metric name prefix: "{{ env('ASDF', 'blahblahblah') }}"

reporting_tasks:
- name: metrics-reporting-task
  config:
    package_id: org.apache.nifi.metrics.reporting.task.MetricsReportingTask
    properties:
      metric reporter service: "{{ controller('graphite-metrics-service') }}"
    # TODO: allow process group lookup by flow name
    # process group id: "{{ flow('flow-name') }}"
