nifi_endpoint: http://nifi-dev:8080
registry_endpoint: http://localhost:18080
zookeeper_connection: nifi-dev:2181

component_dir: components
# documentation_dir: docs

# zookeeper_root_node: /nifi
# zookeeper_acl: open

# max_event_driven_threads: 10
# max_timer_driven_threads: 5

reporting_task_controllers:
- name: graphite-metrics-service
  config:
    package_id: org.apache.nifi.metrics.reporting.reporter.service.GraphiteMetricReporterService
    properties:
      host: '127.0.0.1'
      port: '8080'
      metric name prefix: "{{ env('ASDF', 'blahblahblah') }}"

reporting_tasks:
- name: metrics-reporting-task
  config:
    package_id: org.apache.nifi.metrics.reporting.task.MetricsReportingTask
    properties:
      metric reporter service: "{{ controller('graphite-metrics-service') }}"
    # TODO: allow process group lookup by flow name
    # process group id: "{{ flow('flow-name') }}"
