apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: b23-data-platform

commonLabels:
  environment: local
  owner: b23-data-platform

bases:
- ../app/common

resources:
- ./nifi-service.yaml
- ./nifi.yaml
