apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      imagePullSecrets:
      - name: aws-ecr-registry
      containers:
      - name: nifi
        image: 883886641571.dkr.ecr.us-east-1.amazonaws.com/b23-flowlib:latest
        imagePullPolicy: Always
        env:
        - name: NIFI_WEB_HTTP_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - bash
            - "-c"
            - "curl http://127.0.0.1:8080/nifi"
          initialDelaySeconds: 120
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
        ports:
        - name: nifi-http
          containerPort: 8080
