apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: system
  labels:
    app: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  serviceName: nifi-service
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: dbkegley/nifi:1.8.0
        imagePullPolicy: Always
        env:
        - name: NIFI_WEB_HTTP_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIFI_WEB_HTTP_PORT
          value: "8081"
        ports:
        - name: nifi-http
          containerPort: 8081
