apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-1
spec:
  capacity:
    storage: 512M
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-storage-class
  local:
    path: /tmp/docker/zookeeper/pv1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-for-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-2
spec:
  capacity:
    storage: 512M
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-storage-class
  local:
    path: /tmp/docker/zookeeper/pv2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-for-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-3
spec:
  capacity:
    storage: 512M
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-storage-class
  local:
    path: /tmp/docker/zookeeper/pv3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-for-desktop
