apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: b23-data-platform

commonLabels:
  environment: gcp
  owner: b23-data-platform

resources:
- ./storageclass-gcp.yaml

bases:
- ../../app/common
- ../../app/nifi
- ../../app/zookeeper
