apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - nifi
            topologyKey: "kubernetes.io/hostname"
